version: "3.3"
services:
    db:
        image: mdillon/postgis:11-alpine
        restart: always
        env_file:
            - ./config/db.env
        volumes:
            - db:/var/lib/postgresql/data
        networks:
            db:
                aliases:
                    - db
        ports: 
            - 5432:5432

    redis:
        image: redis
        restart: always
        env_file:
            - ./config/redis.env
        volumes:
            - redis:/data
        networks:
            redis:
                aliases:
                    - redis
        ports: 
            - 6379:6379
   


volumes:
    db:
    redis:

networks:
    db:
    redis: